<?php

/**
 * @file
 *
 * This module provides comment follow-up e-mail notification for anonymous and registered users.
 */

use Drupal\comment\CommentInterface;
use Drupal\Component\Utility\Html;
use Drupal\Component\Utility\Unicode;
use Drupal\Core\Language\LanguageInterface;

define('COMMENT_NOTIFY_DISABLED', 'none');
define('COMMENT_NOTIFY_NODE', 'node');
define('COMMENT_NOTIFY_COMMENT', 'comment');


//define('AUTHOR_MAILTEXT',
//'Hi [comment:node:author],
//
//You have received a comment on: "[comment:node:title]"
//
//----
//[comment:title]
//[comment:body]
//----
//
//You can view the comment at the following url
//[comment:url]
//
//You will receive emails like this for all replies to your posts. You can
//disable this by logging in and changing the settings on your user account at
//[comment:node:author:edit-url].
//
//-- [site:name] team
//[site:url]');

//define('DEFAULT_MAILTEXT',
//'Hi [comment-subscribed:author],
//
//[comment:author] has commented on: "[comment:node:title]"
//
//----
//[comment:title]
//[comment:body]
//----
//
//You can view the comment at the following url
//[comment:url]
//
//You can stop receiving emails when someone replies to this post,
//by going to [comment-subscribed:unsubscribe-url]
//
//You can set up auto-following feature for all future posts
//by creating your own user with a few clicks here [site:login-url]
//
//-- [site:name] team
//[site:url]');


/**
 * Implements hook_init().
 */
function comment_notify_init() {
  // Add on every page - they are both very small so it's better to add
  // everywhere than force a second file on some pages.
  $options = array('every_page' => TRUE);
  $path = drupal_get_path('module', 'comment_notify');
  // @FIXME
// The Assets API has totally changed. CSS, JavaScript, and libraries are now
// attached directly to render arrays using the #attached property.
// 
// 
// @see https://www.drupal.org/node/2169605
// @see https://www.drupal.org/node/2408597
// drupal_add_css($path . '/comment_notify.css', $options);


  // We only add the JS if more than one subscription mode is enabled.
  $available_options = _comment_notify_options();
  if (count($available_options) > 1) {
    // @FIXME
// The Assets API has totally changed. CSS, JavaScript, and libraries are now
// attached directly to render arrays using the #attached property.
// 
// 
// @see https://www.drupal.org/node/2169605
// @see https://www.drupal.org/node/2408597
// drupal_add_js($path . '/comment_notify.js', $options);

  }
}

/**
 * Provide an array of available options for notification on a comment.
 */
function _comment_notify_options() {
  $total_options = array(
    COMMENT_NOTIFY_NODE     => t('All comments'),
    COMMENT_NOTIFY_COMMENT  => t('Replies to my comment')
  );

  $selected_options = array_filter(\Drupal::config('comment_notify.settings')->get('available_alerts'));
  $available_options = array_intersect_key($total_options, $selected_options);

  return $available_options;
}


function comment_notify_form_comment_form_alter(&$form, &$form_state, $form_id) {
  $user = \Drupal::currentUser();
  if (!(\Drupal::currentUser()->hasPermission('subscribe to comments') || \Drupal::currentUser()->hasPermission('administer comments'))) {
    return;
  }

  // Only add the checkbox if this is an enabled content type
  $node = \Drupal::entityManager()->getStorage('node')->load($form['nid']['#value'] ? $form['nid']['#value'] : $form['nid']['#default_value']);
  // @FIXME
// Could not extract the default value because it is either indeterminate, or
// not scalar. You'll need to provide a default value in
// config/install/comment_notify.settings.yml and config/schema/comment_notify.schema.yml.
$enabled_types = \Drupal::config('comment_notify.settings')->get('node_types');
  if (empty($enabled_types[$node->type])) {
    return;
  }

  $available_options = _comment_notify_options();
  // Add the checkbox for anonymous users.
  if ($user->uid == 0) {
    // If anonymous users can't enter their e-mail don't tempt them with the checkbox.
    if (empty($form['author']['mail'])) {
      return;
    }
    $form['#validate'][] = 'comment_notify_comment_validate';
  }
  module_load_include('inc', 'comment_notify', 'comment_notify');
  $preference = comment_notify_get_user_comment_notify_preference($user->uid);

  // If you want to hide this on your site see http://drupal.org/node/322482
  $form['notify_settings']['notify'] = array(
    '#type' => 'checkbox',
    '#title' => t('Notify me when new comments are posted'),
    '#default_value' => (bool) $preference,
  );

  $form['notify_settings']['notify_type'] = array(
    '#type' => 'radios',
    '#options' => $available_options,
    '#default_value' => $preference ? $preference : 1,
  );
  if (count($available_options) == 1) {
    $form['notify_settings']['notify_type']['#type'] = 'hidden';
    $form['notify_settings']['notify_type']['#value'] = key($available_options);
  }

  // If this is an existing comment we set the default value based on their selection last time.
  if ($form['cid']['#value'] != '') {
    $notify = comment_notify_get_notification_type($form['cid']['#value']);
    $form['notify_settings']['notify']['#default_value'] = (bool) $notify;
    if (count($available_options) > 1) {
      $form['notify_settings']['notify_type']['#default_value'] = empty($notify) ? COMMENT_NOTIFY_NODE : $notify;
    }
    else {
      $form['notify_settings']['notify_type']['#default_value'] = key($available_options);
    }
  }
}

/**
 * Implements hook_permission().
 */
function comment_notify_permission() {
  return array(
    'administer comment notify' => array(
      'title' => 'Administer Comment Notify',
      'description' => 'Change global comment notification settings.',
  ),
    'subscribe to comments' => array(
      'title' => 'Subscribe to comment notifications',
      'description' => 'Subscribe to recieve notifications when new comments are posted.',
  ),
  );
}

/**
 * Implements hook_menu().
 */
function comment_notify_menu() {

  $items['admin/config/people/comment_notify'] = array(
    'title' => 'Comment Notify',
    'description' => 'Configure settings for e-mails about new comments.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('comment_notify_settings'),
    'access arguments' => array('administer comment notify'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/people/comment_notify/settings'] = array(
    'title' => 'Settings',
    'description' => 'Configure settings for e-mails about new comments.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('comment_notify_settings'),
    'access arguments' => array('administer comment notify'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/config/people/comment_notify/unsubscribe'] = array(
    'title' => 'Unsubscribe',
    'description' => 'Unsubscribe an email from all notifications.',
    'weight' => 2,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('comment_notify_unsubscribe'),
    'access arguments' => array('administer comment notify'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['comment_notify/disable/%'] = array(
    'title' => 'Disable comment notification',
    'page callback' => 'comment_notify_disable_page',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

/**
 * Page callback to allow users to unsubscribe simply by visiting the page.
 */
function comment_notify_disable_page($hash) {
  module_load_include('inc', 'comment_notify', 'comment_notify');
  if (comment_notify_unsubscribe_by_hash($hash)) {
    return(t('Your comment follow-up notification for this post was disabled. Thanks.'));
  }
  else {
    return(t('Sorry, there was a problem unsubscribing from notifications.'));
  }
}

function comment_notify_comment_validate($comment) {
  $user = \Drupal::currentUser();
  // We assume that if they are non-anonymous then they have a valid mail.
  // For anonymous users, though, we verify that they entered a mail and let comment.module validate it is real.
  if (!$user->uid && $comment['notify_settings']['notify']['#value'] && empty($comment['author']['mail']['#value'])) {
    form_set_error('mail', t('If you want to subscribe to comments you must supply a valid e-mail address.'));
  }
}

function comment_notify_comment_publish($comment) {
  // And send notifications - the real purpose of the module.
  _comment_notify_mailalert($comment);
}

/**
 * Implements hook_comment_update().
 */
function comment_notify_comment_update($comment) {
  module_load_include('inc', 'comment_notify', 'comment_notify');

  // Take the status of the "notify" checkbox if they unchecked it.
  if (empty($comment->notify)) {
    $status = COMMENT_NOTIFY_DISABLED;
  }
  else {
    $status = $comment->notify_type;
  }
  // In case they have changed their status, save it in the database.
  if (isset($status)) {
    comment_notify_update_notification($comment->cid, $status);
  }
  // And send notifications - the real purpose of the module.
  if ($comment->status == COMMENT_PUBLISHED) {
    _comment_notify_mailalert($comment);
  }

}

/**
 * Implements hook_comment_insert().
 */
function comment_notify_comment_insert(\Drupal\comment\CommentInterface $comment) {
  module_load_include('inc', 'comment_notify', 'comment_notify');

  $user = \Drupal::currentUser();
  // For new comments, we first build up a string to be used as the identifier for the alert.
  // This identifier is used to later unsubscribe the user or allow them to
  // potentially edit their comment / preferences if they are anonymous.
  // The string is built with token and their host and comment identifier.
  // It is stored and referenced, we really just need something unique/unguessable.
  $hostname = !$comment->getHostname() ? $comment->getHostname() : (isset($user->hostname) ? $user->hostname : '');
  $notify_hash = drupal_get_token($hostname . $comment->id());

  if (!empty($comment->notify)) {
    $notify = $comment->notify_type;
    // If they don't have a preference, save one.
    $current = comment_notify_get_user_comment_notify_preference($user->uid);
    if ($current == 0 && $user->uid) {
      comment_notify_set_user_notification_setting($user->uid, NULL, $comment->notify_type);
    }
  }
  else {
    $notify = 0;
  }
  // And then save the data.
  comment_notify_add_notification($comment->id(), $notify, $notify_hash);

  // And send notifications - the real purpose of the module.
  if ($comment->isPublished() == COMMENT_PUBLISHED) {
    _comment_notify_mailalert($comment);
  }
}

function comment_notify_comment_delete(\Drupal\comment\CommentInterface $comment) {
  module_load_include('inc', 'comment_notify', 'comment_notify');
  comment_notify_remove_all_notifications($comment->id());
}


/**
 * Implement hook_form_alter().
 */
function comment_notify_form_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state, $form_id) {
  module_load_include('inc', 'comment_notify', 'comment_notify');

  if (!($form_id == 'user_register_form' || $form_id == 'user_profile_form')) {
    return;
  }
  elseif ($form['#user_category'] != 'account') {
    return;
  }

  $user = $form['#user'];
  if (!empty($user->comment_notify_settings)) {
    $node_notify = $user->comment_notify_settings->node_notify;
    $comment_notify = $user->comment_notify_settings->comment_notify;
  }

  $form['comment_notify_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Comment follow-up notification settings'),
    '#weight' => 4,
    '#collapsible' => TRUE
  );

  // Only show the node followup UI if the user has permission to create nodes.
  $nodes = FALSE;
  foreach (node_type_get_names() as $type => $name) {
    if (node_access('create', $type)) {
      $nodes = TRUE;
      break;
    }
  }

  if (\Drupal::currentUser()->hasPermission('administer nodes') || $nodes) {
    $form['comment_notify_settings']['node_notify'] = array(
      '#type' => 'checkbox',
      '#title' => t('Receive content follow-up notification e-mails'),
      '#default_value' => isset($node_notify) ? $node_notify : \Drupal::config('comment_notify.settings')->get('enable_default.entity_author'),
      '#description' => t('Check this box to receive an e-mail notification for follow-ups on your content. You can not disable notifications for individual threads.')
    );
  }
  else {
    $form['comment_notify_settings']['node_notify'] = array(
      '#type' => 'hidden',
      '#value' => COMMENT_NOTIFY_DISABLED,
    );
  }

  $available_options[COMMENT_NOTIFY_DISABLED] = t('No notifications');
  $available_options += _comment_notify_options();
  $form['comment_notify_settings']['comment_notify'] = array(
    '#type' => 'select',
    '#title' => t('Receive comment follow-up notification e-mails'),
    '#default_value' => isset($comment_notify) ? array($comment_notify) : array(\Drupal::config('comment_notify.settings')->get('enable_default.watcher')),
    '#options' => $available_options,
    '#description' => t("Check this box to receive e-mail notification for follow-up comments to comments you posted. You can later disable this on a post-by-post basis... so if you leave this to YES, you can still disable follow-up notifications for comments you don't want follow-up mails anymore - i.e. for very popular posts.")
  );
  return $form;
  // Construct the user form
}

/**
 * @FIXME
 * The $edit and $category parameters are gone in Drupal 8. They have been left
 * here in order to prevent 'undefined variable' errors, but they will never
 * actually be passed to this hook. You'll need to modify this function and
 * remove every reference to them.
 */
function comment_notify_user_update(\Drupal\user\UserInterface $account, $category, $edit = NULL) {
  if ($category != 'account') {
    return;
  }
  if (isset($edit['node_notify']) && isset($edit['comment_notify'])) {
    module_load_include('inc', 'comment_notify', 'comment_notify');

    // Save the values of node_notify_mailalert and comment_notify_mailalert
    // to {comment_notify_user_settings}.
    comment_notify_set_user_notification_setting($account->id(), $edit['node_notify'], $edit['comment_notify']);
  }
  // Unset them from $user so they don't also get saved into {users}.data.
  unset($edit['node_notify']);
  unset($edit['comment_notify']);

}

function comment_notify_user_load($users) {
  module_load_include('inc', 'comment_notify', 'comment_notify');

  // @todo: Why would we want to load this on every user load?
  foreach ($users as &$user) {
    $user->comment_notify_settings = comment_notify_get_user_notification_setting($user->uid);
  }

  return;
}

function comment_notify_user_cancel($edit, $account, $method) {
  module_load_include('inc', 'comment_notify', 'comment_notify');
  comment_notify_delete_user_notification_setting($account->uid);
}

/**
 * Implements hook_comment_load().
 */
function comment_notify_comment_load($comments) {
  // Load some comment_notify specific information into the comment object.
  $query = db_select('comment_notify', 'cn');
  $query->join('comment', 'c', 'c.cid = cn.cid');
  $query->leftJoin('users', 'u', 'c.uid = u.uid');
  $query->condition('c.cid', array_keys($comments));
  $query->fields('cn', array('cid', 'notify', 'notify_hash', 'notified'));
  $query->addField('c', 'mail', 'cmail');
  $query->addField('u', 'init', 'uinit');
  $query->addField('u', 'mail', 'umail');

  $records = $query->execute()->fetchAllAssoc('cid');
  foreach ($records as $cid => $record) {
    $comments[$cid]->notify = $record->notify;
    $comments[$cid]->notify_type = $record->notify;
    $comments[$cid]->notify_hash = $record->notify_hash;
    $comments[$cid]->notified = $record->notified;
    $comments[$cid]->cmail = $record->cmail;
    $comments[$cid]->uinit = $record->uinit;
    $comments[$cid]->umail = $record->umail;
  }
}

/**
 * Private function to send the notifications.
 *
 * @param \Drupal\comment\CommentInterface $comment
 *   The comment entity.
 */
function _comment_notify_mailalert(CommentInterface $comment) {
  module_load_include('inc', 'comment_notify', 'comment_notify');

  $config = \Drupal::config('comment_notify.settings');
  $user = \Drupal::currentUser();
  $nid = $comment->getCommentedEntityId();

  // Check to see if a notification has already been sent for this
  // comment so that edits to a comment don't trigger an additional
  // notification.
  if (!empty($comment->notified)) {
    return;
  }

  /** @var \Drupal\node\NodeInterface $node */
  $node = \Drupal::entityManager()->getStorage('node')->load($nid);

  // No mails if this is not an enabled content type.
  $enabled_types = $config->get('node_types') ?: [$node->getEntityTypeId()];
  if (empty($enabled_types[$node->getEntityTypeId()])) {
    return;
  }

  if (empty($comment->mail)) {
    $comment_account = user_load_by_name($comment->getAuthorName());
    $comment_mail = isset($comment_account->mail) ? $comment_account->mail : '';
  }
  else {
    $comment_mail = $comment->mail;
  }
  $sent_to = array();

  // Send to a subscribed author if they are not the current commenter.
  $author = $node->getOwner();

  // Do they explicitly want this? Or is it default to send to users?
  // Is the comment author not the node author? Do they have access? Do they have an email (e.g. anonymous)?
  if (
    (
      (!empty($author->comment_notify_settings->node_notify) && $author->comment_notify_settings->node_notify == 1)
      || ($config->get('enable_default.entity_author') == 1 && !isset($author->comment_notify_settings->node_notify))
    )
    && $user->id() != $author->id()
    && $node->access('view', $author)
    && !empty($author->getEmail())
  ) {
    // Get the author's language.
    $language = $author->getPreferredLangcode();
    $raw_values = array(
      'subject' => $config->get('mail_templates.entity_author.subject'),
      'body'  => $config->get('mail_templates.entity_author.body'),
    );
    foreach ($raw_values as $k => $v) {
      $message[$k] = \Drupal::token()->replace(t($v), array('comment' => $comment), array('sanitize' => FALSE));
    }

    \Drupal::service('plugin.manager.mail')->mail('comment_notify', 'comment_notify_mail', $author->getEmail(), $language, $message);
    $sent_to[] = strtolower($author->getEmail());
  }

  // For "reply to my comments" notifications, figure out what thread this is.
  $thread = $comment->getThread() ?: '';

  // Get the list of commenters to notify.
  $watchers = comment_notify_get_watchers($nid);

  foreach ($watchers as $alert) {
    // If the user is not anonymous, always load the current e-mail address
    // from his or her user account instead of trusting $comment->mail.
    $recipient_user = $alert->getOwner();
    $mail = !empty($recipient_user->getEmail()) ? $recipient_user->getEmail() : $alert->getAuthorEmail();

    $relevant_thread = Unicode::substr($thread, 0, Unicode::strlen($alert->getThread()) -1);
    if ($alert->notify == COMMENT_NOTIFY_COMMENT && strcmp($relevant_thread . '/', $alert->getThread()) != 0) {
      continue;
    }

    if ($mail != $comment_mail && !in_array(strtolower($mail), $sent_to) && ($alert->getOwnerId() != $comment->getOwnerId() || $alert->getOwnerId() == 0)) {

      $message = array();
      $language = !empty($alert->uid) ? $recipient_user->getPreferredLangcode() : LanguageInterface::LANGCODE_DEFAULT;

      // Make sure they have access to this node before showing a bunch of node information.
      if (!$node->access('view', $recipient_user)) {
        continue;
      }

      $raw_values = array(
        'subject' => $config->get('mail_templates.watcher.subject'),
        'body'  => $config->get('mail_templates.watcher.body'),
      );

      foreach ($raw_values as $k => $v) {
        $message[$k] = \Drupal::token()->replace(t($v), array('comment' => $comment, 'comment-subscribed' => $alert), array('sanitize' => FALSE));
      }

      \Drupal::service('plugin.manager.mail')->mail('comment_notify', 'comment_notify_mail', $mail, $language, $message);
      $sent_to[] = strtolower($mail);

      // Make the mail link to user's /edit, unless it's an anonymous user.
      if ($alert->getOwnerId() != 0) {
        $user_mail = $alert->link($mail, 'edit-form');
      }
      else {
        $user_mail = Html::escape($mail);
      }

      // Add an entry to the watchdog log.
      \Drupal::logger('comment_notify')->notice('Notified: @user_mail', ['@user_mail' => $user_mail, 'link' => $alert->link(t('source comment'))]);
    }
  }
  // Record that a notification was sent for this comment so that
  // notifications aren't sent again if the comment is later edited.
  comment_notify_mark_comment_as_notified($comment);
}

/**
 * Implements hook_mail().
 */
function comment_notify_mail($key, &$message, $params) {
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['body'];
}

/**
 * Callback for an administrative form to unsubscribe users by e-mail address.
 */
function comment_notify_unsubscribe($form, &$form_state) {
  $form['comment_notify_unsubscribe'] = array();
  $form['comment_notify_unsubscribe']['email_to_unsubscribe'] = array(
    '#type' => 'textfield',
    '#title' => t('Email to unsubscribe'),
  );
  $form['comment_notify_unsubscribe']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Unsubscribe this e-mail'),
  );
  return $form;
}

/**
 * Based on admin submit, do the actual unsubscribe from notifications.
 */
function comment_notify_unsubscribe_submit($form, &$form_state) {
  module_load_include('inc', 'comment_notify', 'comment_notify');
  $email = trim($form_state['values']['email_to_unsubscribe']);
  $comments = comment_notify_unsubscribe_by_email($email);
  // Update the admin about the state of this comment notification subscription.
  if ($comments == 0) {
    drupal_set_message(t("There were no active comment notifications for that email."));
  }
  else {
    drupal_set_message(\Drupal::translation()->formatPlural($comments, "Email unsubscribed from 1 comment notification.",
      "Email unsubscribed from @count comment notifications."));
  }
}

/**
 * Get the unsubscribe link for a comment subscriber.
 *
 * @param $comment
 *   The subscribed comment object.
 *
 * @return
 *   A string with the internal path to the unsubscribe link, ready to be
 *   passed to the url() function.
 */
function comment_notify_get_unsubscribe_url($comment) {
  module_load_include('inc', 'comment_notify', 'comment_notify');
  if (!empty($comment->notify_hash)) {
    return 'comment_notify/disable/' . $comment->notify_hash;
  }
}
/**
 * Implements hook_field_extra_fields().
 */
function comment_notify_field_extra_fields() {
  module_load_include('inc', 'comment_notify', 'comment_notify');
  $extras = array();

  foreach (\Drupal::config('comment_notify.settings')->get('node_types') as $node_type) {
    if (isset($node_type)) {
      $extras['comment']['comment_node_' . $node_type]['form']['comment_notify_settings'] = array(
        'label' => t('Comment Notify settings'),
        'description' => t('@node_type settings for Comment Notify', array('@node_type' => ucwords($node_type))),
        'weight' => 1,
      );
    }
  }

  $extras['user']['user']['form']['comment_notify_settings'] = array(
    'label' => t('Comment Notify settings'),
    'description' => t('User settings for Comment Notify'),
    'weight' => 4,
  );
  return $extras;
}

